---
abstract: 'R language build on Perl'
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Rstats
no_index:
  directory:
    - t
    - inc
requires:
  Math::Round: '0.06'
  Object::Simple: '3.10'
  Text::UnicodeTable::Simple: '0.09'
version: '0.0108'
