/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.24 from the
 * contents of Rstats.xs. Do not edit this file, edit Rstats.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Rstats.xs"
/* Rstats headers */
#include "Rstats.h"

/* Perl headers */
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "ppport.h"

/* avoid symbol collisions*/
#undef init_tm
#undef do_open
#undef do_close
#ifdef ENTER
#undef ENTER
#endif

#include "RstatsPerlAPI.h"

Rstats::PerlAPI* p = new Rstats::PerlAPI;

using namespace std;

#line 34 "Rstats.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 176 "Rstats.c"

XS_EUPXS(XS_Rstats__ElementXS_is_finite); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementXS_is_finite)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 29 "Rstats.xs"
{
  Rstats::Element* self = p->to_c_obj<Rstats::Element*>(ST(0));

  SV* ret_sv;
  if (self->type == Rstats::ElementType::INTEGER || (self->type == Rstats::ElementType::DOUBLE && isfinite(self->dv))) {
    ret_sv = p->new_sv((I32)1);
  }
  else {
    ret_sv = p->new_sv((I32)0);
  }

  return_sv(ret_sv);
}
#line 200 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementXS_is_infinite); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementXS_is_infinite)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 46 "Rstats.xs"
{
  Rstats::Element* self = p->to_c_obj<Rstats::Element*>(ST(0));

  int ret = Rstats::ElementFunc::is_infinite(self);

  return_sv(p->new_sv((I32)ret));
}
#line 223 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementXS_is_nan); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementXS_is_nan)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 57 "Rstats.xs"
{
  Rstats::Element* self = p->to_c_obj<Rstats::Element*>(ST(0));

  SV* ret_sv;
  if (self->type == Rstats::ElementType::DOUBLE && isnan(self->dv)) {
    ret_sv = p->new_sv((I32)1);
  }
  else {
    ret_sv = p->new_sv((I32)0);
  }

  return_sv(ret_sv);
}
#line 252 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementXS_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementXS_type)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 74 "Rstats.xs"
{
  Rstats::Element* self = p->to_c_obj<Rstats::Element*>(ST(0));

  // Type
  Rstats::ElementType::Enum type = self->type;
  SV* type_sv;
  if (type == Rstats::ElementType::NA) {
    type_sv = p->new_sv("na");
  }
  else if (type == Rstats::ElementType::LOGICAL) {
    type_sv = p->new_sv("logical");
  }
  else if (type == Rstats::ElementType::INTEGER) {
    type_sv = p->new_sv("integer");
  }
  else if (type == Rstats::ElementType::DOUBLE) {
    type_sv = p->new_sv("double");
  }
  else if (type == Rstats::ElementType::COMPLEX) {
    type_sv = p->new_sv("complex");
  }
  else if (type == Rstats::ElementType::CHARACTER) {
    type_sv = p->new_sv("character");
  }
  else if (type == Rstats::ElementType::UNKNOWN) {
    type_sv = p->new_sv("unknown");
  }

  return_sv(type_sv);
}
#line 298 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementXS_iv); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementXS_iv)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 108 "Rstats.xs"
{
  Rstats::Element* self = p->to_c_obj<Rstats::Element*>(ST(0));

  I32 iv = self->iv;

  return_sv(p->new_sv(iv));
}
#line 321 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementXS_dv); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementXS_dv)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 119 "Rstats.xs"
{
  Rstats::Element* self = p->to_c_obj<Rstats::Element*>(ST(0));

  double dv = self->dv;

  return_sv(p->new_sv(dv));
}
#line 344 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementXS_cv); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementXS_cv)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 130 "Rstats.xs"
{
  Rstats::Element* self = p->to_c_obj<Rstats::Element*>(ST(0));

  SV* chv_sv = p->new_sv(self->chv);

  return_sv(chv_sv);
}
#line 367 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementXS_re); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementXS_re)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 141 "Rstats.xs"
{
  Rstats::Element* self = p->to_c_obj<Rstats::Element*>(ST(0));

  double re = ((complex<double>*)self->pv)->real();

  SV* re_sv;
  if (isinf(re)) {
    if (re > 0) {
      re_sv = p->new_sv("Inf");
    }
    else {
      re_sv = p->new_sv("-Inf");
    }
  }
  else if(isnan(re)) {
    re_sv = p->new_sv("NaN");
  }
  else {
    re_sv = p->new_sv(re);
  }

  return_sv(re_sv);
}
#line 406 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementXS_im); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementXS_im)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 168 "Rstats.xs"
{
  Rstats::Element* self = p->to_c_obj<Rstats::Element*>(ST(0));

  double im = ((complex<double>*)self->pv)->imag();

  SV* im_sv;
  if (isinf(im)) {
    if (im > 0) {
      im_sv = p->new_sv("Inf");
    }
    else {
      im_sv = p->new_sv("-Inf");
    }
  }
  else if(isnan(im)) {
    im_sv = p->new_sv("NaN");
  }
  else {
    im_sv = p->new_sv(im);
  }

  return_sv(im_sv);
}
#line 445 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementXS_flag); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementXS_flag)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 195 "Rstats.xs"
{
  Rstats::Element* self = p->to_c_obj<Rstats::Element*>(ST(0));

  SV* flag_sv;
  if (self->type == Rstats::ElementType::DOUBLE) {
    if (isinf(self->dv)) {
      if (self->dv > 0) {
        flag_sv = p->new_sv("inf");
      }
      else {
        flag_sv = p->new_sv("-inf");
      }
    }
    else if(isnan(self->dv)) {
      flag_sv = p->new_sv("nan");
    }
    else {
      flag_sv = p->new_sv("normal");
    }
  }
  else {
    flag_sv = p->new_sv("normal");
  }

  return_sv(flag_sv);
}
#line 487 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementXS_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementXS_DESTROY)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 225 "Rstats.xs"
{
  Rstats::Element* self = p->to_c_obj<Rstats::Element*>(ST(0));
  if (self->type == Rstats::ElementType::COMPLEX) {
    delete (complex<double>*)self->pv;
  }
  else if (self->type == Rstats::ElementType::CHARACTER) {
    delete self->chv;
  }
  delete self;
}
#line 513 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementFunc_negativeInf_xs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementFunc_negativeInf_xs)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 241 "Rstats.xs"
{
  Rstats::Element* element = Rstats::ElementFunc::create_double(-(INFINITY));
  SV* element_obj = p->to_perl_obj(element, "Rstats::ElementXS");

  return_sv(element_obj);
}
#line 535 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementFunc_Inf_xs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementFunc_Inf_xs)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 251 "Rstats.xs"
{
  Rstats::Element* element = Rstats::ElementFunc::create_double(INFINITY);
  SV* element_obj = p->to_perl_obj(element, "Rstats::ElementXS");

  return_sv(element_obj);
}
#line 557 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementFunc_NaN_xs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementFunc_NaN_xs)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 261 "Rstats.xs"
{
  Rstats::Element* element = Rstats::ElementFunc::create_double(NAN);
  SV* element_obj = p->to_perl_obj(element, "Rstats::ElementXS");

  return_sv(element_obj);
}
#line 579 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementFunc_character_xs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementFunc_character_xs)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 271 "Rstats.xs"
{
  SV* value_sv = ST(0);
  char* chv = p->pv(value_sv);

  Rstats::Element* element = new Rstats::Element;
  element->chv = chv;
  element->type = Rstats::ElementType::CHARACTER;

  SV* element_obj = p->to_perl_obj(element, "Rstats::ElementXS");

  return_sv(element_obj);
}
#line 607 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementFunc_complex_xs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementFunc_complex_xs)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 287 "Rstats.xs"
{
  SV* re_sv = ST(0);
  SV* im_sv = ST(1);

  double re = p->nv(re_sv);
  double im = p->nv(im_sv);

  complex<double>* z = new complex<double>(re, im);

  Rstats::Element* element = new Rstats::Element;
  element->pv = (void*)z;
  element->type = Rstats::ElementType::COMPLEX;

  SV* element_obj = p->to_perl_obj(element, "Rstats::ElementXS");

  return_sv(element_obj);
}
#line 640 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementFunc_logical_xs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementFunc_logical_xs)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 308 "Rstats.xs"
{
  SV* value_sv = ST(0);
  I32 iv = p->iv(value_sv);

  Rstats::Element* element = new Rstats::Element;
  element->iv = iv;
  element->type = Rstats::ElementType::LOGICAL;

  SV* element_obj = p->to_perl_obj(element, "Rstats::ElementXS");

  return_sv(element_obj);
}
#line 668 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementFunc_integer_xs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementFunc_integer_xs)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 324 "Rstats.xs"
{
  SV* value_sv = ST(0);
  I32 iv = p->iv(value_sv);

  Rstats::Element* element = new Rstats::Element;
  element->iv = iv;
  element->type = Rstats::ElementType::INTEGER;

  SV* element_obj = p->to_perl_obj(element, "Rstats::ElementXS");

  return_sv(element_obj);
}
#line 696 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__ElementFunc_double_xs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__ElementFunc_double_xs)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 340 "Rstats.xs"
{
  SV* value_sv = ST(0);
  double dv = p->nv(value_sv);

  Rstats::Element* element = Rstats::ElementFunc::create_double(dv);

  SV* element_obj = p->to_perl_obj(element, "Rstats::ElementXS");

  return_sv(element_obj);
}
#line 722 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__Util_cross_product); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__Util_cross_product)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 356 "Rstats.xs"
{
  SV* values_sv = ST(0);

  I32 values_length = p->length(values_sv);
  SV* idxs_sv = p->new_av_ref();
  for (I32 i = 0; i < values_length; i++) {
    p->push(idxs_sv, p->new_sv((I32)0)); 
  }

  SV* idx_idx_sv = p->new_av_ref();
  for (I32 i = 0; i < values_length; i++) {
    p->push(idx_idx_sv, p->new_sv(i));
  }

  SV* x1_sv = p->new_av_ref();
  for (I32 i = 0; i < values_length; i++) {
    SV* value_sv = p->av_get(values_sv, i);
    p->push(x1_sv, p->av_get(value_sv, (I32)0));
  }

  SV* result_sv = p->new_av_ref();
  p->push(result_sv, p->copy_av(x1_sv));
  I32 end_loop = 0;
  while (1) {
    for (I32 i = 0; i < values_length; i++) {

      if (p->iv(p->av_get(idxs_sv, i)) < p->length(p->av_get(values_sv, i)) - 1) {

        SV* idxs_tmp = p->av_get(idxs_sv, i);
        sv_inc(idxs_tmp);
        p->av_set(x1_sv, i, p->av_get(p->av_get(values_sv, i), idxs_tmp));

        p->push(result_sv, p->copy_av(x1_sv));

        break;
      }

      if (i == p->iv(p->av_get(idx_idx_sv, values_length - 1))) {
        end_loop = 1;
        break;
      }

      p->av_set(idxs_sv, i, p->new_sv((I32)0));
      p->av_set(x1_sv, i, p->av_get(p->av_get(values_sv, i), (I32)0));
    }
    if (end_loop) {
      break;
    }
  }

  return_sv(result_sv);
}
#line 790 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__Util_pos_to_index); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__Util_pos_to_index)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 412 "Rstats.xs"
{
  SV* pos_sv = ST(0);
  SV* dim_sv = ST(1);

  SV* index_sv = p->new_av_ref();
  I32 pos = p->iv(pos_sv);
  I32 before_dim_product = 1;
  for (I32 i = 0; i < p->length(p->av_deref(dim_sv)); i++) {
    before_dim_product *= p->iv(p->av_get(dim_sv, i));
  }

  for (I32 i = p->length(p->av_deref(dim_sv)) - 1; i >= 0; i--) {
    I32 dim_product = 1;
    for (I32 k = 0; k < i; k++) {
      dim_product *= p->iv(p->av_get(dim_sv, k));
    }

    I32 reminder = pos % before_dim_product;
    I32 quotient = (int)(reminder / dim_product);

    p->unshift(index_sv, p->new_sv(quotient + 1));
    before_dim_product = dim_product;
  }

  return_sv(index_sv);
}
#line 832 "Rstats.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Rstats__Util_index_to_pos); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Rstats__Util_index_to_pos)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 442 "Rstats.xs"
{
  SV* index_sv =ST(0);
  SV* dim_values_sv = ST(1);

  U32 pos = 0;
  for (U32 i = 0; i < p->length(p->av_deref(dim_values_sv)); i++) {
    if (i > 0) {
      U32 tmp = 1;
      for (U32 k = 0; k < i; k++) {
        tmp *= p->uv(p->av_get(dim_values_sv, k));
      }
      pos += tmp * (p->uv(p->av_get(index_sv, i)) - 1);
    }
    else {
      pos += p->uv(p->av_get(index_sv, i));
    }
  }

  SV* pos_sv = p->new_sv(pos - 1);

  return_sv(pos_sv);
}
#line 870 "Rstats.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Rstats); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Rstats)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Rstats::ElementXS::is_finite", XS_Rstats__ElementXS_is_finite, file);
        newXS("Rstats::ElementXS::is_infinite", XS_Rstats__ElementXS_is_infinite, file);
        newXS("Rstats::ElementXS::is_nan", XS_Rstats__ElementXS_is_nan, file);
        newXS("Rstats::ElementXS::type", XS_Rstats__ElementXS_type, file);
        newXS("Rstats::ElementXS::iv", XS_Rstats__ElementXS_iv, file);
        newXS("Rstats::ElementXS::dv", XS_Rstats__ElementXS_dv, file);
        newXS("Rstats::ElementXS::cv", XS_Rstats__ElementXS_cv, file);
        newXS("Rstats::ElementXS::re", XS_Rstats__ElementXS_re, file);
        newXS("Rstats::ElementXS::im", XS_Rstats__ElementXS_im, file);
        newXS("Rstats::ElementXS::flag", XS_Rstats__ElementXS_flag, file);
        newXS("Rstats::ElementXS::DESTROY", XS_Rstats__ElementXS_DESTROY, file);
        newXS("Rstats::ElementFunc::negativeInf_xs", XS_Rstats__ElementFunc_negativeInf_xs, file);
        newXS("Rstats::ElementFunc::Inf_xs", XS_Rstats__ElementFunc_Inf_xs, file);
        newXS("Rstats::ElementFunc::NaN_xs", XS_Rstats__ElementFunc_NaN_xs, file);
        newXS("Rstats::ElementFunc::character_xs", XS_Rstats__ElementFunc_character_xs, file);
        newXS("Rstats::ElementFunc::complex_xs", XS_Rstats__ElementFunc_complex_xs, file);
        newXS("Rstats::ElementFunc::logical_xs", XS_Rstats__ElementFunc_logical_xs, file);
        newXS("Rstats::ElementFunc::integer_xs", XS_Rstats__ElementFunc_integer_xs, file);
        newXS("Rstats::ElementFunc::double_xs", XS_Rstats__ElementFunc_double_xs, file);
        newXS("Rstats::Util::cross_product", XS_Rstats__Util_cross_product, file);
        newXS("Rstats::Util::pos_to_index", XS_Rstats__Util_pos_to_index, file);
        newXS("Rstats::Util::index_to_pos", XS_Rstats__Util_index_to_pos, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

